// Generated by AI
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  HostAgentRuntime,
  ModelRuntime,
  SessionManager,
  SettingsManager,
  createAgentCoreSession,
  createAssistantMessageEventStream,
  type AssistantMessage,
  type Classifier,
  type ClassifierAnswers,
  type ClassifierQuestions,
  type FelanExtension,
  type StreamFunction,
  type TranscriptContext,
} from '@felan-ai/agent-core';
import prewalkExtension from '@felan-ai/ext-prewalk';
import { createSubagentsExtension, type SubagentHost } from '@felan-ai/ext-subagents';
import tasksExtension from '@felan-ai/ext-tasks';
import { afterEach, describe, expect, it, vi } from 'vitest';

type Session = Awaited<ReturnType<typeof createAgentCoreSession>>['session'];
type Step = Pick<Extract<AssistantMessage['content'][number], { type: 'toolCall' }>, 'name' | 'arguments'> | 'final';
type Script = (context: TranscriptContext) => Step;
type ClassificationState = {
  request?: string;
  session?: {
    conversation: { role: string; text: string }[];
    verification_after_last_mutation?: boolean;
    failed_verification?: boolean;
  };
  extensions?: {
    thinking?: Record<string, unknown>;
    subagents?: { active_children: unknown[]; discovery_agent: { id: string } };
    prewalk?: { profiles: { key: string; model: string; thinking: string; tier: string }[] };
  };
};

const temporaryPaths: string[] = [];
const sessions: Session[] = [];
const producerQuestions = ['prewalk:planner', 'prewalk:route', 'subagents:broad_discovery', 'thinking:effort'];

afterEach(async () => {
  sessions.splice(0).forEach(session => session.dispose());
  vi.restoreAllMocks();
  await Promise.all(temporaryPaths.splice(0).map(path => rm(path, { force: true, recursive: true })));
});

describe('composed turn classification', () => {
  it('shares one preflight, owns planning and implementation effort, then restores regular routing', async () => {
    const harness = await createHarness();
    const { session, settings, calls, streams, high, low, host, cwd } = harness;
    const defaults = selectionDefaults(settings);
    harness.script(implementationScript(true));
    const prompt = 'Inspect the repository, plan the fixture change, implement it and verify it. Do not launch children.';

    await session.prompt(prompt);

    expect(session.messages.filter(message => message.role === 'toolResult' && message.isError)).toEqual([]);
    expect(session.messages.filter(message => message.role === 'assistant' && message.stopReason === 'error')).toEqual([]);
    expect(calls.map(call => Object.keys(call.questions).sort())).toEqual([
      producerQuestions,
      ['depth'],
      ['thinking', 'tier'],
      ['verdict'],
    ]);
    const initial = calls[0]!;
    expect(initial.state.request).toBe(prompt);
    expect(initial.state.session).toMatchObject({ conversation: [], tool_activity: [] });
    expect(initial.state.extensions).toMatchObject({
      thinking: {},
      subagents: { active_children: [], discovery_agent: { id: 'explore' } },
      prewalk: { profiles: expect.arrayContaining([
        expect.objectContaining({ model: `${high.provider}/${high.id}`, tier: 'high', thinking: 'high' }),
      ]) },
    });
    expect(Object.keys(initial.state.extensions!).sort()).toEqual(['prewalk', 'subagents', 'thinking']);
    expect(initial.state.extensions!.subagents).not.toHaveProperty('session');
    expect(initial.state.extensions!.prewalk).not.toHaveProperty('session');
    expect(streams.map(({ model, thinking }) => [model, thinking])).toEqual([
      [high.id, 'low'],
      [high.id, 'high'],
      [high.id, 'high'],
      [high.id, 'high'],
      [low.id, 'medium'],
      [low.id, 'medium'],
      [low.id, 'medium'],
    ]);
    expect(discoveryGuidance(streams[0]!.context)).toContain('Delegate that discovery to `explore`');
    expect(contextText(streams[0]!.context)).toContain('Call `enter_prewalk` as the only tool call');
    expect(contextText(streams[1]!.context)).toContain('Exploration depth: targeted');
    expect(contextText(streams[4]!.context)).toContain('Continue implementing the existing session task graph');
    expect(calls.at(-1)!.state.session).toMatchObject({
      verification_after_last_mutation: true,
      failed_verification: false,
    });
    expect(await readFile(join(cwd, 'fixture-0.txt'), 'utf8')).toBe('after\n');
    expect(session.model?.id).toBe(high.id);
    expect(session.thinkingLevel).toBe('low');
    expect(selectionDefaults(settings)).toEqual(defaults);
    expect(streams.every(stream => JSON.stringify(stream.defaults) === JSON.stringify(defaults))).toBe(true);
    expect(host.spawn).not.toHaveBeenCalled();

    harness.script(() => 'final');
    await session.prompt('Summarize the verified change without modifying anything.');

    expect(calls).toHaveLength(5);
    expect(Object.keys(calls[4]!.questions).sort()).toEqual(producerQuestions);
    expect(calls[4]!.state.session!.conversation.length).toBeGreaterThan(0);
    expect(streams.at(-1)).toMatchObject({ model: high.id, thinking: 'low' });
    expect(contextText(streams.at(-1)!.context)).not.toContain('Exploration depth: targeted');
    expect(selectionDefaults(settings)).toEqual(defaults);
    expect(host.list).toHaveBeenCalledTimes(2);
    expect(host.spawn).not.toHaveBeenCalled();
  });

  it('keeps discovery guidance when command-armed Prewalk promotes the model before other consumers run', async () => {
    const harness = await createHarness({ startLow: true });
    const { session, settings, calls, streams, high, low, host } = harness;
    const defaults = selectionDefaults(settings);
    await session.prompt('/prewalk');
    expect(streams).toHaveLength(0);
    expect(calls).toHaveLength(0);
    harness.script(implementationScript(false));

    await session.prompt('Plan, update and verify the fixture without launching children.');

    expect(session.messages.filter(message => message.role === 'toolResult' && message.isError)).toEqual([]);
    expect(session.messages.filter(message => message.role === 'assistant' && message.stopReason === 'error')).toEqual([]);
    expect(Object.keys(calls[0]!.questions).sort()).toEqual([
      'prewalk:planner', 'subagents:broad_discovery', 'thinking:effort',
    ]);
    expect(calls.map(call => Object.keys(call.questions).sort())).toEqual([
      ['prewalk:planner', 'subagents:broad_discovery', 'thinking:effort'],
      ['depth'], ['thinking', 'tier'], ['verdict'],
    ]);
    expect(streams.map(({ model, thinking }) => [model, thinking])).toEqual([
      [high.id, 'high'], [high.id, 'high'], [high.id, 'high'],
      [low.id, 'medium'], [low.id, 'medium'], [low.id, 'medium'],
    ]);
    expect(discoveryGuidance(streams[0]!.context)).toContain('Delegate that discovery to `explore`');
    expect(session.model?.id).toBe(low.id);
    expect(session.thinkingLevel).toBe('medium');
    expect(selectionDefaults(settings)).toEqual(defaults);
    expect(host.list).toHaveBeenCalledTimes(1);
    expect(host.spawn).not.toHaveBeenCalled();
  });

  it('honors manual thinking opt-out without disabling the other classification producers', async () => {
    const { session, calls, streams, settings, high, host } = await createHarness();
    await session.prompt('Summarize the repository.');
    expect(streams[0]).toMatchObject({ model: high.id, thinking: 'low' });
    await session.prompt('/prewalk');
    session.setThinkingLevel('medium');
    await new Promise<void>(resolve => setImmediate(resolve));
    const manualDefaults = selectionDefaults(settings);

    await session.prompt('Continue with my selected reasoning effort, without entering Prewalk.');

    expect(calls).toHaveLength(2);
    expect(Object.keys(calls[1]!.questions).sort()).toEqual([
      'prewalk:planner', 'prewalk:route', 'subagents:broad_discovery',
    ]);
    expect(streams.at(-1)).toMatchObject({ model: high.id, thinking: 'medium' });
    expect(contextText(streams.at(-1)!.context)).not.toContain('Exploration depth: targeted');
    expect(discoveryGuidance(streams.at(-1)!.context)).toContain('Delegate that discovery to `explore`');
    expect(selectionDefaults(settings)).toEqual(manualDefaults);
    expect(host.spawn).not.toHaveBeenCalled();
  });

  it('cancels command-armed promotion after a manual model selection', async () => {
    const { session, calls, streams, settings, low, host } = await createHarness();
    await session.prompt('/prewalk');
    await session.setModel(low);
    const manualDefaults = selectionDefaults(settings);

    await session.prompt('Use my selected model for a regular response.');

    expect(calls).toHaveLength(1);
    expect(Object.keys(calls[0]!.questions)).toContain('prewalk:route');
    expect(streams).toHaveLength(1);
    expect(streams[0]!.model).toBe(low.id);
    expect(session.model?.id).toBe(low.id);
    expect(contextText(streams[0]!.context)).not.toContain('Exploration depth: targeted');
    expect(discoveryGuidance(streams[0]!.context)).toContain('Delegate that discovery to `explore`');
    expect(selectionDefaults(settings)).toEqual(manualDefaults);
    expect(host.spawn).not.toHaveBeenCalled();
  });

  it('cancels planning when the user explicitly reselects its current high effort', async () => {
    const harness = await createHarness();
    const script = implementationScript(true);
    harness.script(context => {
      if (harness.streams.length === 2) harness.session.setThinkingLevel('high');
      return script(context);
    });

    await harness.session.prompt('Plan, update and verify the fixture.');

    expect(harness.streams[1]).toMatchObject({ model: harness.high.id, thinking: 'high' });
    expect(harness.streams.slice(1).every(stream => stream.model === harness.high.id && stream.thinking === 'high')).toBe(true);
    expect(harness.session.model?.id).toBe(harness.high.id);
    expect(harness.session.thinkingLevel).toBe('high');
    expect(harness.session.messages.filter(message => message.role === 'toolResult' && message.isError)).toEqual([]);
  });

  it('invalidates pending ordinary effort when the user reselects the current level', async () => {
    const harness = await createHarness();
    let entered!: () => void;
    let release!: () => void;
    const pending = new Promise<void>(resolve => { entered = resolve; });
    const resume = new Promise<void>(resolve => { release = resolve; });
    const classify = harness.classifier.classify.bind(harness.classifier);
    vi.spyOn(harness.classifier, 'classify').mockImplementationOnce(async (...args) => {
      const result = await classify(...args);
      entered();
      await resume;
      return result;
    });
    const prompt = harness.session.prompt('Summarize the repository without changing files.');
    await pending;
    harness.session.setThinkingLevel('high');
    release();
    await prompt;

    expect(harness.streams.at(-1)).toMatchObject({ model: harness.high.id, thinking: 'high' });
    await harness.session.prompt('Keep using my chosen reasoning effort.');
    expect(Object.keys(harness.calls.at(-1)!.questions)).not.toContain('thinking:effort');
    expect(harness.session.thinkingLevel).toBe('high');
  });

  it('does not mistake an implicit same-level model clamp for a manual effort choice', async () => {
    const harness = await createHarness();
    await harness.session.setModel(harness.high);

    await harness.session.prompt('Summarize the repository without changing files.');

    expect(Object.keys(harness.calls[0]!.questions)).toContain('thinking:effort');
    expect(harness.streams.at(-1)).toMatchObject({ model: harness.high.id, thinking: 'low' });
  });

  it('preserves a same-level manual effort selection during an in-flight handoff', async () => {
    const harness = await createHarness();
    let entered!: () => void;
    let release!: () => void;
    const pending = new Promise<void>(resolve => { entered = resolve; });
    const resume = new Promise<void>(resolve => { release = resolve; });
    const setModel = harness.session.setModel.bind(harness.session);
    vi.spyOn(harness.session, 'setModel').mockImplementationOnce(async (...args) => {
      entered();
      await resume;
      return setModel(...args);
    });
    harness.script(implementationScript(true));
    const prompt = harness.session.prompt('Plan, update and verify the fixture.');
    await pending;
    expect(harness.session.thinkingLevel).toBe('high');
    harness.session.setThinkingLevel('high');
    release();
    await prompt;

    expect(harness.session.thinkingLevel).toBe('high');
    expect(harness.streams.slice(4).every(stream => stream.thinking === 'high')).toBe(true);
    expect(harness.session.messages.filter(message => message.role === 'toolResult' && message.isError)).toEqual([]);
  });
});

async function createHarness(options: { startLow?: boolean } = {}) {
  const root = await mkdtemp(join(tmpdir(), 'felan-turn-classification-'));
  temporaryPaths.push(root);
  const cwd = join(root, 'workspace');
  const agentDir = join(root, 'agent');
  await Promise.all([cwd, agentDir, join(root, 'session-storage'), join(root, 'agent-storage')]
    .map(path => mkdir(path, { recursive: true })));
  await Promise.all(Array.from({ length: 24 }, (_, index) => writeFile(join(cwd, `fixture-${index}.txt`), 'before\n')));
  const modelRuntime = await ModelRuntime.create({ authPath: join(agentDir, 'auth.json'), modelsPath: null });
  const high = modelRuntime.getModel('openai-codex', 'gpt-6.1-sol');
  const low = modelRuntime.getModel('openai-codex', 'gpt-6-luna');
  if (!high || !low) throw new Error('Expected official GPT-6 planning and implementation models');
  vi.spyOn(modelRuntime, 'hasConfiguredAuth').mockReturnValue(true);
  vi.spyOn(modelRuntime, 'checkAuth').mockResolvedValue({} as never);
  const calls: { state: ClassificationState; questions: ClassifierQuestions }[] = [];
  const classifier: Classifier = {
    async classify(rawState, questions) {
      const state = rawState as ClassificationState;
      calls.push({ state: structuredClone(state), questions });
      const answers: Record<string, ClassifierAnswers[string]> = {};
      for (const id of Object.keys(questions)) {
        if (id === 'subagents:broad_discovery') {
          answers[id] = { type: 'bool', probability: 0.9 };
          continue;
        }
        const planner = state.extensions?.prewalk?.profiles.find(profile =>
          profile.model === `${high.provider}/${high.id}` && profile.thinking === 'high');
        const choices: Record<string, string | undefined> = {
          'thinking:effort': 'low', 'prewalk:route': 'prewalk', 'prewalk:planner': planner?.key,
          depth: 'targeted', tier: 'high', thinking: 'high', verdict: 'done',
        };
        const choice = choices[id];
        if (!choice) throw new Error(`Unexpected classifier question or missing planner profile: ${id}`);
        answers[id] = { type: 'choice', choice };
      }
      return { answers };
    },
  };
  const runtime = new HostAgentRuntime(cwd, {
    sessionStorageRoot: join(root, 'session-storage'),
    agentStorageRoot: join(root, 'agent-storage'),
    agentDir,
    classifier,
  });
  const host = {
    descriptors: [{ id: 'explore', description: 'Read-only investigation', allowNesting: false }],
    policy: { maxPromptBytes: 10_000, maxDescriptionBytes: 1_000, maxSteerBytes: 1_000 },
    attachParent: vi.fn(() => () => {}),
    spawn: vi.fn(async () => { throw new Error('Child execution is prohibited in this fixture'); }),
    list: vi.fn(async () => ({ ok: true as const, value: [] })),
    getResult: vi.fn(), steer: vi.fn(), cancel: vi.fn(),
  };
  const extensions: Record<string, FelanExtension> = {
    '@felan-ai/ext-codex': () => {},
    '@felan-ai/ext-prewalk': prewalkExtension,
    '@felan-ai/ext-subagents': createSubagentsExtension(host as unknown as SubagentHost),
    '@felan-ai/ext-tasks': tasksExtension,
  };
  const initial = options.startLow ? low : high;
  const settings = SettingsManager.inMemory({
    defaultProvider: initial.provider,
    defaultModel: initial.id,
    defaultThinkingLevel: options.startLow ? 'medium' : 'high',
  });
  const streams: { model: string; thinking: string; context: TranscriptContext; defaults: ReturnType<typeof selectionDefaults> }[] = [];
  let next: Script = () => 'final';
  let session: Session;
  const stream: StreamFunction = (model, context) => {
    streams.push({ model: model.id, thinking: session.thinkingLevel, context: structuredClone(context), defaults: selectionDefaults(settings) });
    const step = next(context);
    const message: AssistantMessage = {
      role: 'assistant', api: model.api, provider: model.provider, model: model.id,
      content: step === 'final' ? [{ type: 'text', text: 'Fixture changed and verification passed.' }]
        : [{ type: 'toolCall', id: `tool-${streams.length}`, name: step.name, arguments: step.arguments }],
      stopReason: step === 'final' ? 'stop' : 'toolUse',
      usage: { input: 1, output: 1, cacheRead: 0, cacheWrite: 0, totalTokens: 2,
        cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } },
      timestamp: Date.now(),
    };
    const response = createAssistantMessageEventStream();
    queueMicrotask(() => {
      response.push({ type: 'start', partial: { ...message, content: [], stopReason: 'pending' } });
      response.push({ type: 'done', reason: step === 'final' ? 'stop' : 'toolUse', message });
    });
    return response;
  };
  ({ session } = await createAgentCoreSession({
    runtime, modelRuntime, agentDir, model: initial,
    thinkingLevel: options.startLow ? 'medium' : 'high',
    scopedModels: [{ model: high, thinkingLevel: 'high' }, { model: low, thinkingLevel: 'medium' }],
    dynamicThinking: true,
    settingsManager: settings,
    sessionManager: SessionManager.inMemory(cwd),
    extensionPackages: Object.keys(extensions),
    importExtension: async name => ({ default: extensions[name] }),
    extensionConfigOverrides: [{ extensionId: 'prewalk', source: 'test', values: {
      entryApproval: 'allow', planReview: 'skip', targetModel: 'low', targetThinking: 'medium', restorePlanner: true,
    } }],
    wrapStreamFunction: () => stream,
  }));
  sessions.push(session);
  await session.bindExtensions({ mode: 'rpc' });
  return { session, settings, calls, streams, high, low, host, cwd, classifier, script: (script: Script) => { next = script; } };
}

function implementationScript(enter: boolean): Script {
  let index = 0;
  return context => {
    const results = context.messages.filter(message => message.role === 'toolResult');
    expect(results.filter(result => result.isError)).toEqual([]);
    const created = results.find(result => result.toolName === 'TaskCreate');
    const taskId = created && textContent(created.content).match(/T-[A-Z0-9]{6}/)?.[0];
    const steps: Step[] = [
      ...(enter ? [{ name: 'enter_prewalk', arguments: {} }] : []),
      { name: 'TaskCreate', arguments: { title: 'Update fixture', acceptance_criteria: 'Fixture reads after and shell test passes' } },
      { name: 'TaskUpdate', arguments: { task_id: taskId ?? '', status: 'in_progress' } },
      { name: 'edit', arguments: { path: 'fixture-0.txt', oldText: 'before', newText: 'after' } },
      { name: 'bash', arguments: { command: 'test "$(cat fixture-0.txt)" = after' } },
      { name: 'TaskUpdate', arguments: { task_id: taskId ?? '', status: 'completed', result: 'Shell test confirmed fixture content is after' } },
      'final',
    ];
    const step = steps[index++];
    if (!step) throw new Error('Unexpected continuation beyond the verified scripted final response');
    if (step !== 'final' && step.name === 'TaskUpdate') expect(taskId).toMatch(/^T-[A-Z0-9]{6}$/);
    return step;
  };
}

function selectionDefaults(settings: SettingsManager) {
  return { provider: settings.getDefaultProvider(), model: settings.getDefaultModel(), thinking: settings.getDefaultThinkingLevel() };
}

function discoveryGuidance(context: TranscriptContext) {
  return context.messages.find(message => message.role === 'system')?.sections?.subagent_routing;
}

function contextText(context: TranscriptContext) {
  return context.messages.map(message => 'content' in message ? textContent(message.content) : '').join('\n');
}

function textContent(content: string | readonly { type: string; text?: string }[]) {
  return typeof content === 'string' ? content : content.filter(part => part.type === 'text').map(part => part.text ?? '').join('\n');
}
