export const packagePaths = [
  'packages/agent-core',
  'packages/ext-memory',
  'packages/ext-subagents',
  'packages/ext-ask-user',
  'packages/ext-tasks',
  'packages/ext-context',
  'packages/ext-prewalk',
  'packages/ext-markitdown',
  'packages/ext-background-bash',
  'packages/ext-browser',
  'packages/ext-web-access',
  'packages/ext-mcp',
  'packages/ext-codex',
  'packages/ext-rtk-optimizer',
  'packages/ext-powerline',
  'apps/tui',
];
